import ChannelNavBar from "@/components/NavBars/ChannelNavBar.tsx";
import AppLayout from "@/layouts/AppLayout.tsx";

const Guild = () => {

    return (
        <AppLayout>
            <ChannelNavBar>
                <>
                thisisatest
                thisisatest
                thisisatest
                thisisatest
                thisisatest
                thisisatest
                thisisatest
                thisisatest
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                test
                </>
            </ChannelNavBar>
        </AppLayout>
    );
};

export default Guild;
