import DmNavBar from "@/components/NavBars/ChannelNavBar.tsx";
import MemberBar from "@/components/NavBars/MemberBar.tsx";
import AppLayout from "@/layouts/AppLayout.tsx";

const Guild = () => {

    return (
        <AppLayout>
            <DmNavBar>
                thisisatest
                thisisatest
                thisisatest
                thisisatest
                thisisatest
                thisisatest
                thisisatest
                thisisatest
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                t
                test
            </DmNavBar>
        </AppLayout>
    );
};

export default Guild;
